### ISSUE TITLE
Not resolving package names

### ISSUE THREAD

**Issue by cadorn** [noffle/git-ssb-intro#10]
Using `ssb-server` **without** `Patchwork`.

When I call `npm install --registry=http://localhost:8043/ -g ssb-npm`, I get:

```
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for ssb-npm
```

I traced it a bit and it looks like the npm-registry plugin cannot find any mentions using the links2 index.

That makes me think I am not following the right people to get the messages that have the package release mentions?
I did follow `cel` but it must not be downloading all the messages? My `.ssb` directory  is `873876` bytes in size and not growing.

How can I tell `ssb-server` to download the relevant messages so I can resolve the package names to their blobs?

**Comment by cadorn** [comment]
Just found https://github.com/noffle/ssb-npm-101

Calling `ssb-server messagesByType npm-packages | grep -C 1 ssb-npm-registry` gives me nothing while `ssb-server messagesByType npm-packages` does give me some results.

**Comment by cadorn** [comment]
I was able to install `git-ssb` using: https://git.scuttlebot.io/%25n92DiQh7ietE%2BR%2BX%2FI403LQoyf2DtR3WQfCkDKlheQU%3D.sha256/blob/8ca97332f9199fc7faf0dc1e971a36bc032e9bd0/git-ssb-2.7.0-binary-install.sh

**Comment by hackergrrl** [comment]
You can check if you have all of cel's messages with

```
ssb-server createHistoryStream --id '@f/6sQ6d2CMxRUhLpspgGIulDxDCwYD7DzFzPNr7u5AU=.ed25519' | wc -l
```
I get 16000 currently.

**Comment by cadorn** [comment]
Thanks for the help. There is a steep learning curve to get into ssb.

When I run `ssb-server createHistoryStream` commands I get a bunch of JSON objects so when I count these with `wc -l` I get a much higher count. How do you get `createHistoryStream` to print out one line per message? I am running `ssb-server@^15.2.0`. Is that the latest?

I have two `.ssb` databases setup. One for patchwork which has many more of cal's messages and one with just `ssb-server` which has way fewer. Both DBs follow the same publisher. On the patchwork one I am following a few more people.

How do I instruct `ssb-server` to download more of cal`s messages?
Should that happen by default by merely following him? Could my `ssb-server` be misconfigured and thus not downloading messages? I have not set the external IP in the configuration.

I have patchwork open and am mutually befriended with the `ssb-server` based DB but cal`s messages are not being copied over from the patchwork DB to the other one. How can I cause `ssb-server` to do that?

The above issue seems to be the main problem I have in understanding and succeeding with the intro and it appears other users are running into the same as well.

**Comment by hackergrrl** [comment]
Hey Christoph,

> There is a steep learning curve to get into ssb.

There really is! I'm pleased you've stayed with it :)

> When I run `ssb-server createHistoryStream` commands I get a bunch of
> JSON objects so when I count these with `wc -l` I get a much higher
> count. How do you get `createHistoryStream` to print out one line per
> message? I am running `ssb-server@^15.2.0`. Is that the latest?

If you add a grep for a key in the json structure, like "author", you'll
get something smaller.

```
~$ ssb-server createHistoryStream --id '@f/6sQ6d2CMxRUhLpspgGIulDxDCwYD7DzFzPNr7u5AU=.ed25519' | grep author | wc -l
16163
```

If you see a number in that range, you likely have the full feed
downloaded.

> I have two `.ssb` databases setup. One for patchwork which has many
> more of cal's messages and one with just `ssb-server` which has way
> fewer. Both DBs follow the same publisher. On the patchwork one I am
> following a few more people.

Try the patchwork db with the install instructions too! Maybe that one
will work.

> How do I instruct `ssb-server` to download more of cal`s messages?
> Should that happen by default by merely following him? Could my
> `ssb-server` be misconfigured and thus not downloading messages?

SSB automatically downloads all history when you follow
someone. If that number looks like mine, try the ssb-npm installation
instructions again -- perhaps it just needed time to catch up.

> I have patchwork open and am mutually befriended with the `ssb-server`
> based DB but cal`s messages are not being copied over from the
> patchwork DB to the other one. How can I cause `ssb-server` to do
> that?

I'm not sure what's happening here. Where are your two .ssb folders
located?

**Comment by cadorn** [comment]
It appears all it took was time. The patchwork DB caught up after a day and I now have a bunch of `git-ssb` messages:

    ssb-server messagesByType npm-packages | grep -C 1 git-ssb

I am also running an instance of `ssb-server` with `export ssb_appname=ssb-mytest` set and configured to run on different ports so it does not conflict with patchwork. This DB has also caught up so all appears to be working now.

Thanks for your help!

**Comment by hackergrrl** [comment]
@cadorn you're welcome, glad you figured it out
