### ISSUE TITLE
Github != Git

### ISSUE THREAD

**Issue by lil5** [noffle/git-ssb-intro#4]
From reading the `readme` it seems that the writer does not know the difference between Git and Github

> Git is a revision control system, a tool to manage your source code history.
>
> GitHub is a hosting service for Git repositories.
>
>So they are not the same thing: Git is the tool, GitHub is the service for projects that use Git.
>
> <https://stackoverflow.com/a/13321586>

**Comment by hackergrrl** [comment]
Hey @lil5. Could you expand on where in the doc you think I've gotten confused? I'd also be very happy to accept a PR that clarifies this. Thanks!

**Comment by lil5** [comment]
Yes i have gotten very confused
Although I'm still not sure...

By the wording I guess you're using "Github" to mean "a Git server with issue & activity tracking and merge diff under a web interface." but I sooner took the distinction that "Github" as the company.

For example this sentence, to me, doesn't make cense:

```
I find BitBucket a great service for a Github workflow.
```

**Comment by hackergrrl** [comment]
@lil5 Are there certain phrases in the readme that you feel are confusing? If you can point some out to me I'm sure we can clarify them.
