### ISSUE TITLE
where to find sbot?

### ISSUE THREAD

**Issue by cbluth** [noffle/git-ssb-intro#9]
i am running patchwork with the appimage, is that all that is required?

i want to install `ssb-npm-registry` and `ssb-npm`, but the guide is failing at these commands

**Comment by hackergrrl** [comment]
Does `ssb-server` work? `sbot` was renamed a little while ago.

If not, you can use npm to install it:

npm install --global ssb-server

then use it instead of `sbot` in the instructions.

**Comment by interfect** [comment]
How do you make sure you have the right `sbot` or `ssb-server` for your Patchwork?

**Comment by hackergrrl** [comment]
@interfect I'm not sure how Patchwork handles this.
